Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'node_modules/**'
    - 'public/**'
    - 'tmp/**'
    - 'vendor/**'
    - 'log/**'